"""Initial revision

Revision ID: 3cea710e10b1
Revises: 349c52b48661
Create Date: 2025-01-01 22:42:53.901309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cea710e10b1'
down_revision: Union[str, None] = '349c52b48661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocodes', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promocodes', 'id')
    # ### end Alembic commands ###
