"""Initial revision

Revision ID: 84932c23dda4
Revises: 57e82c83cd03
Create Date: 2024-12-05 21:21:00.005969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84932c23dda4'
down_revision: Union[str, None] = '57e82c83cd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocodes', sa.Column('uses_left', sa.Integer(), nullable=False))
    op.drop_column('promocodes', 'user_left')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocodes', sa.Column('user_left', sa.INTEGER(), nullable=False))
    op.drop_column('promocodes', 'uses_left')
    # ### end Alembic commands ###
