"""Initial revision

Revision ID: ac4d8ec7fab7
Revises: 
Create Date: 2024-12-30 20:55:05.249759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4d8ec7fab7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_streak', sa.Integer(), nullable=False),
    sa.Column('bonus_cm', sa.Integer(), nullable=False),
    sa.Column('bonus_attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocodes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('uses_left', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('last_grow', sa.Date(), nullable=False),
    sa.Column('bonus_attempts', sa.Integer(), nullable=False),
    sa.Column('grow_streak', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('uses_of_promo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['promocodes.code_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uses_of_promo')
    op.drop_table('users')
    op.drop_table('promocodes')
    op.drop_table('bonuses')
    # ### end Alembic commands ###
